apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-service
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 32002
  selector:
    service: mysql