server:
  port: 8281

spring:
  application:
    name: education-service
  sleuth:
    enabled: true
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411

# Spring Cloud Kubernetes 연동
  cloud:
    kubernetes:
      reload:
        enable: true
ribbon:
  http:
    client:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
