server:
  port: 8081

spring:
  application:
    name: student-service
  sleuth:
    enabled: true
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411

# Spring Cloud Kubernetes 연동
  cloud:
    kubernetes:
      reload:
        enable: true
      secrets:
        name: db-secret
  data:
    mongodb:
      host: localhost
      port: 31418
      database: admin
      username: kido
      password: 1234qwer

# Spring Actuator Management Endpoint config
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    restart:
      enabled: true
