server:
  port: 8081

spring:
  application:
    name: student-service
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin-service:9411

# Spring Cloud Kubernetes 연동
  cloud:
    kubernetes:
      reload:
        enable: true
      secrets:
        name: db-secret
  data:
    mongodb:
      host: mongodb-service
      port: 27017
      database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

# Spring Actuator Management Endpoint config
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    restart:
      enabled: true
