server:
  port: 8181

spring:
  application:
    name: professor-service
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin-service:9411

  # Spring Cloud Kubernetes 연동
  cloud:
    kubernetes:
      reload:
        enable: true
      secrets: mysql-db-secret
  datasource:
    url: jdbc:mysql://mysql-service:3306/professor?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect